export { default as PageHOC } from "./PageHOC";
export { default as CustomInput } from "./CustomInput";
export { default as CustomButton } from "./CustomButton";
export { default as Alert } from "./Alert";
export { default as GameLoad } from "./GameLoad";
export { default as ActionButton } from "./ActionButton";
export { default as Card } from "./Card";
export { default as GameInfo } from "./GameInfo";
export { default as PlayerInfo } from "./PlayerInfo";
